name: Cross Browser - Cypress Tests

on: [push]

# New commit on branch cancels running workflows of the same branch
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-chrome:
    uses: roselandroche/cypress-practice/.github/workflows/cypress-chrome.yml@main
  
  test-firefox:
    uses:  roselandroche/cypress-practice/.github/workflows/cypress-firefox.yml@main
  
  test-edge:
    uses:  roselandroche/cypress-practice/.github/workflows/cypress-edge.yml@main
