name: Cross Browser - Cypress Tests

on: [push]

jobs:
  chrome:
    uses: roselandroche/cypress-practice/.github/workflows/cypress-chrome.yml@main
  
  edge:
    uses:  roselandroche/cypress-practice/.github/workflows/cypress-edge.yml@main
  
  firefox:
    uses:  roselandroche/cypress-practice/.github/workflows/cypress-firefox.yml@main
