name: Cypress Tests - Edge

on: workflow_call

jobs:
  edge:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
          headless: true
