name: Cypress Tests using Cypress Docker Image

on: [push]

jobs:
  firefox:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
          headless: true
  chrome:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
  edge:
    runs-on: windows-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: edge
