name: Cypress Tests - Firefox

on: workflow_call

jobs:
  firefox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
          headless: true
